{
 "title": "Postman Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "collection", "label": "Collection", "query": { "query": "postman_stats_iterations_total" } }
  ]
 },
 "panels": [
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "postman_timings_resp_avg", "legendFormat": "{{collection}} avg" },
    { "expr": "postman_timings_resp_max", "legendFormat": "{{collection}} max" },
    { "expr": "postman_timings_resp_min", "legendFormat": "{{collection}} min" }
   ]
  },
  {
   "title": "Assertion Failures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postman_stats_assertions_failed/postman_stats_assertions_total",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Request Failures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postman_stats_requests_failed/postman_stats_requests_total",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Test Failures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postman_stats_tests_failed/postman_stats_tests_total",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(postman_lifetime_requests_total[2m])",
     "legendFormat": "{{collection}}"
    }
   ]
  }
 ]
}