{
 "title": "Postman Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "jsonname", "label": "JSON Name", "query": { "query": "postman_stats_iterations_total" } }
  ]
 },
 "panels": [
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "postman_timings_resp_avg{json_name=\"$jsonname\"}",
     "legendFormat": "{{json_name}} avg"
    },
    {
     "expr": "postman_timings_resp_max{json_name=\"$jsonname\"}",
     "legendFormat": "{{json_name}} max"
    },
    {
     "expr": "postman_timings_resp_min{json_name=\"$jsonname\"}",
     "legendFormat": "{{json_name}} min"
    }
   ]
  },
  {
   "title": "Assertion Failures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postman_stats_assertions_failed{json_name=\"$jsonname\"}/postman_stats_assertions_total{json_name=\"$jsonname\"}"
    }
   ]
  },
  {
   "title": "Request Failures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postman_stats_requests_failed{json_name=\"$jsonname\"}/postman_stats_requests_total{json_name=\"$jsonname\"}"
    }
   ]
  },
  {
   "title": "Test Failures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postman_stats_tests_failed{json_name=\"$jsonname\"}/postman_stats_tests_total{json_name=\"$jsonname\"}"
    }
   ]
  }
 ]
}